//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoletoCaixaService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo", ConfigurationName="BoletoCaixaService.manutencao_cobranca_bancaria")]
    public interface manutencao_cobranca_bancaria
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="IncluiBoleto", ReplyAction="*")]
        System.Threading.Tasks.Task<BoletoCaixaService.INCLUI_BOLETOResponse> INCLUI_BOLETOAsync(BoletoCaixaService.INCLUI_BOLETORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BaixaBoleto", ReplyAction="*")]
        System.Threading.Tasks.Task<BoletoCaixaService.BAIXA_BOLETOResponse> BAIXA_BOLETOAsync(BoletoCaixaService.BAIXA_BOLETORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AlteraBoleto", ReplyAction="*")]
        System.Threading.Tasks.Task<BoletoCaixaService.ALTERA_BOLETOResponse> ALTERA_BOLETOAsync(BoletoCaixaService.ALTERA_BOLETORequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SERVICO_ENTRADA", WrapperNamespace="http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo", IsWrapped=true)]
    public partial class INCLUI_BOLETORequest
    {
        
        public INCLUI_BOLETORequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SERVICO_SAIDA", WrapperNamespace="http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo", IsWrapped=true)]
    public partial class INCLUI_BOLETOResponse
    {
        
        public INCLUI_BOLETOResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SERVICO_ENTRADA", WrapperNamespace="http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo", IsWrapped=true)]
    public partial class BAIXA_BOLETORequest
    {
        
        public BAIXA_BOLETORequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SERVICO_SAIDA", WrapperNamespace="http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo", IsWrapped=true)]
    public partial class BAIXA_BOLETOResponse
    {
        
        public BAIXA_BOLETOResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SERVICO_ENTRADA", WrapperNamespace="http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo", IsWrapped=true)]
    public partial class ALTERA_BOLETORequest
    {
        
        public ALTERA_BOLETORequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SERVICO_SAIDA", WrapperNamespace="http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto/externo", IsWrapped=true)]
    public partial class ALTERA_BOLETOResponse
    {
        
        public ALTERA_BOLETOResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface manutencao_cobranca_bancariaChannel : BoletoCaixaService.manutencao_cobranca_bancaria, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class manutencao_cobranca_bancariaClient : System.ServiceModel.ClientBase<BoletoCaixaService.manutencao_cobranca_bancaria>, BoletoCaixaService.manutencao_cobranca_bancaria
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public manutencao_cobranca_bancariaClient() : 
                base(manutencao_cobranca_bancariaClient.GetDefaultBinding(), manutencao_cobranca_bancariaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.manutencao_cobranca_bancariaSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public manutencao_cobranca_bancariaClient(EndpointConfiguration endpointConfiguration) : 
                base(manutencao_cobranca_bancariaClient.GetBindingForEndpoint(endpointConfiguration), manutencao_cobranca_bancariaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public manutencao_cobranca_bancariaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(manutencao_cobranca_bancariaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public manutencao_cobranca_bancariaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(manutencao_cobranca_bancariaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public manutencao_cobranca_bancariaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoletoCaixaService.INCLUI_BOLETOResponse> BoletoCaixaService.manutencao_cobranca_bancaria.INCLUI_BOLETOAsync(BoletoCaixaService.INCLUI_BOLETORequest request)
        {
            return base.Channel.INCLUI_BOLETOAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoletoCaixaService.INCLUI_BOLETOResponse> INCLUI_BOLETOAsync()
        {
            BoletoCaixaService.INCLUI_BOLETORequest inValue = new BoletoCaixaService.INCLUI_BOLETORequest();
            return ((BoletoCaixaService.manutencao_cobranca_bancaria)(this)).INCLUI_BOLETOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoletoCaixaService.BAIXA_BOLETOResponse> BoletoCaixaService.manutencao_cobranca_bancaria.BAIXA_BOLETOAsync(BoletoCaixaService.BAIXA_BOLETORequest request)
        {
            return base.Channel.BAIXA_BOLETOAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoletoCaixaService.BAIXA_BOLETOResponse> BAIXA_BOLETOAsync()
        {
            BoletoCaixaService.BAIXA_BOLETORequest inValue = new BoletoCaixaService.BAIXA_BOLETORequest();
            return ((BoletoCaixaService.manutencao_cobranca_bancaria)(this)).BAIXA_BOLETOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BoletoCaixaService.ALTERA_BOLETOResponse> BoletoCaixaService.manutencao_cobranca_bancaria.ALTERA_BOLETOAsync(BoletoCaixaService.ALTERA_BOLETORequest request)
        {
            return base.Channel.ALTERA_BOLETOAsync(request);
        }
        
        public System.Threading.Tasks.Task<BoletoCaixaService.ALTERA_BOLETOResponse> ALTERA_BOLETOAsync()
        {
            BoletoCaixaService.ALTERA_BOLETORequest inValue = new BoletoCaixaService.ALTERA_BOLETORequest();
            return ((BoletoCaixaService.manutencao_cobranca_bancaria)(this)).ALTERA_BOLETOAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.manutencao_cobranca_bancariaSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.manutencao_cobranca_bancariaSOAP))
            {
                return new System.ServiceModel.EndpointAddress("https://des.barramento.caixa.gov.br/sibar/ManutencaoCobrancaBancaria/Boleto/Exter" +
                        "no");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return manutencao_cobranca_bancariaClient.GetBindingForEndpoint(EndpointConfiguration.manutencao_cobranca_bancariaSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return manutencao_cobranca_bancariaClient.GetEndpointAddress(EndpointConfiguration.manutencao_cobranca_bancariaSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            manutencao_cobranca_bancariaSOAP,
        }
    }
}
